package main

import (
	"fmt"
	_"testing"
	"github.com/robertkrimen/otto/ast"
	"github.com/robertkrimen/otto/parser"
	"encoding/json"
	"io/ioutil"
	"os/exec"
	"net/http"
	"net/url"
	"regexp"
	"os"
)


	
type Autogenerated []struct {
	Method string `json:"Method"`
	URL    string `json:"URL"`
	Header struct {
		Accept                  string `json:"Accept"`
		UpgradeInsecureRequests string `json:"Upgrade-Insecure-Requests"`
		UserAgent               string `json:"User-Agent"`
	} `json:"Header"`
}




//func Test_Check_Json() {
//	//CheckJsRespAst()
//	result, err := CheckSenseJsonp("https://accounts.ctrip.com/ssoproxy/ssoGetUserInfo?jsonp=jQuery2398423949823")
//	//result,err := CheckJsRespAst(`/**/callback_bilibili({"nick":"","code":0,"msg":"success","data":{"curPage":1,"pageCount":1,"totalSize":1,"pageSize":1,"data":[{"id":29749652,"title":"榛樿姝屽崟","type":1,"published":0,"cover":"","ctime":1566281377,"song":0,"desc":"","sids":[],"statistic":{"sid":29696064,"play":0,"collect":0,"comment":null,"share":0}}]}});`)
//	fmt.Println(result)
//	fmt.Println(err)
//}




func main() {
	//Test_Check_Json()
	// 获取要扫描的主域名
	domain  := "https://accounts.ctrip.com/ssoproxy/ssoGetUserInfo?jsonp=jQuery2398423949823"
	// 使用rad爬取相关链接
	urls := radscan(domain)
	fmt.Println("解析完成，开始jsonp检测...")

	// 检测jsonp 并发 ，输出要关注的

	for _,url := range urls {
		result, _ := CheckSenseJsonp(url)
		if result {
			fmt.Println("检测存在jsonp问题 ！",url)
		}
	}  
	fmt.Println("扫描完成")
}



//基于AST的JSONP劫持漏洞检测
//1.解析js路径，检查query所有key是否满足正则 (?m)(?i)(callback)|(jsonp)|(^cb$)|(function)
//2.referer配置为同域，请求js获取响应
//3.js响应生成AST，如果满足
//		a) Callee.Name == callback函数名
//		b) 递归遍历AST 获取所有的字段和对应的value
//		c) 字段为敏感字段（满足正则(?m)(?i)(uid)|(userid)|(user_id)|(nin)|(name)|(username)|(nick)），且value不为空
//4.替换Referer后再请求一次，重新验证步骤3
//
//调用方式
//入参：js路径
//返回：是否存在漏洞，err
//result, err := CheckSenseJsonp("http://127.0.0.1/jsonp_env/getUser.php?id=1&jsoncallback=callbackFunction")

func CheckSenseJsonp(jsUrl string)(bool, error){
	// 准备referer
	queryMap, domainString, err := UrlParser(jsUrl)
	if err != nil{
		return false, err
	}
	// 检查jsonp关键字
	isCallback, callbackFuncName, err := CheckJSIsCallback(queryMap)

	if isCallback{
		//	referer： host 请求
		normalRespContent, err := GetJsResponse(jsUrl, domainString)
		if err != nil{
			return false, err
		}
		//  检查JS语句
		isJsonpNormal , err := CheckJsRespAst(normalRespContent, callbackFuncName)
		if err != nil{
			return false, err
		}
		// 如果包含敏感字段 将 referer 置空 再请求一次
		if isJsonpNormal{
			noRefererContent, err := GetJsResponse(jsUrl, "")
			if err != nil{
				return false, err
			}
			isJsonp , err := CheckJsRespAst(noRefererContent, callbackFuncName)
			if err != nil{
				return false, err
			}
			return isJsonp, nil
		}

	}
	return false, nil
}

func UrlParser(jsUrl string)(url.Values, string, error){
	urlParser, err := url.Parse(jsUrl)
	if err != nil{
		return nil, "", err
	}
	// 拼接原始referer
	domainString := urlParser.Scheme + "://" + urlParser.Host
	return urlParser.Query(), domainString, nil
}

func CheckJSIsCallback(queryMap url.Values) (bool,string, error){
	var re = regexp.MustCompile(`(?m)(?i)(callback)|(jsonp)|(^cb$)|(function)`)
	for k, v :=range queryMap {
		regResult := re.FindAllString(k, -1)
		if len(regResult) > 0 && len(v)>0 {
			return true, v[0], nil
		}
	}
	return false, "",nil
}

func CheckIsSensitiveKey(key string) (bool,error) {
	var re = regexp.MustCompile(`(?m)(?i)(uid)|(userid)|(user_id)|(nin)|(name)|(username)|(nick)`)
	regResult := re.FindAllString(key, -1)
	if len(regResult) > 0 {
		return true, nil
	}
	return false, nil
}

func GetJsResponse(jsUrl string, referer string) (string, error) {
	req, err := http.NewRequest("GET", jsUrl, nil)
	if err != nil {
		return "", nil
	}
	req.Header.Set("Referer", referer)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
	if resp.StatusCode == 200 {
		return string(body), nil
	}
	return "", nil
}


func CheckJsRespAst(content string, funcName string) (bool,error){
	// 解析js语句，生成 *ast.Program 或 ErrorList
	program, err := parser.ParseFile(nil, "", content, 0)
	if err != nil{
		return false, err
	}
	if len(program.Body) > 0 {
		statement := program.Body[0]
		expression := statement.(*ast.ExpressionStatement).Expression
		expName := expression.(*ast.CallExpression).Callee.(*ast.Identifier).Name
		// 表达式中函数名与query函数名不一致 直接返回false
		if funcName != expName{
			return false, err
		}
		argList := expression.(*ast.CallExpression).ArgumentList
		for _, arg := range argList{
			result := DealAstExpression(arg)
			if result != true{
				continue
			}
			return result, nil
		}
	}
	//ast树为空 直接返回
	return false, nil
}

func DealAstExpression(expression ast.Expression)bool{
	objectLiteral, isObjectLiteral := expression.(*ast.ObjectLiteral)
	if isObjectLiteral{
		values := objectLiteral.Value
		for _, value := range values{
			result := DealAstProperty(value)
			if result != true{
				continue
			}
			return result
		}
	}
	return false
}
func DealAstProperty(value ast.Property)bool{
	secondLevelValue := value.Value
	// 表达式中是数组/对象的 递归
	objectLiteral, isObjectLiteral := secondLevelValue.(*ast.ObjectLiteral)
	arrayLiteral, isArrayLiteral := secondLevelValue.(*ast.ArrayLiteral)
	stringLiteral, isStringLiteral := secondLevelValue.(*ast.StringLiteral)
	numberLiteral, isNumberLiteral := secondLevelValue.(*ast.NumberLiteral)
	if isObjectLiteral {
		thirdLevelValue := objectLiteral.Value
		for _, v := range thirdLevelValue {
			DealAstProperty(v)
		}
	} else if isArrayLiteral {
		thirdLevelValue := arrayLiteral.Value
		for _, v := range thirdLevelValue {
			DealAstExpression(v)
		}
	} else if isStringLiteral{
	// 表达式中value为字符串/数字的 才会检测key value
		thirdLevelValue := stringLiteral.Value
		isSensitiveKey, _ := CheckIsSensitiveKey(value.Key)
		if isSensitiveKey && thirdLevelValue != ""{
			return true
		}
	} else if isNumberLiteral {
		thirdLevelValue := numberLiteral.Value
		isSensitiveKey, _ := CheckIsSensitiveKey(value.Key)
		if isSensitiveKey && thirdLevelValue != 0{
			return true
		}
	}
	return false
}





func radscan(url string) (urls []string) {

	// 执行扫描，获取结果
	fmt.Println("开始爬取域名：",url)
	filename := "test.json"
	cmd := exec.Command("./rad_darwin_amd64","-t",url,"-json",filename) // ./rad_darwin_amd64 -t https://www.ctrip.com -json result.json
	output, _ := cmd.CombinedOutput()
    fmt.Println(string(output))


    

	// 解析json 获取需要的get 请求
	fmt.Println("爬取完成，开始进行解析读取...")
	b, err := ioutil.ReadFile(filename)  													// json 读取数据
    if err != nil {
        fmt.Print(err)
    }

    var radjson Autogenerated    
    errs := json.Unmarshal(b, &radjson)
    if errs != nil {
        fmt.Println(errs)
        //os.Exit(0)
    }	

    for i := 0 ; i < len(radjson) ; i ++ {    												// 输出 json 数据
        //fmt.Println(radjson[i].Method,radjson[i].URL)
        urls = append(urls,radjson[i].URL)
   	}
   	errss := os.Remove(filename)	     													// 删除下载的文件
   	if errss    != nil { fmt.Println(err) }		
	return urls
}





















