package controllers

import (
	"encoding/json"
	"fmt"
	"github.com/astaxie/beego"
	"io/ioutil"
	"math/rand"
	"net/http"
	"strconv"
	"time"
)

type DNSController struct {
	beego.Controller
}

type Autogenerated struct {
	Meta struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	} `json:"meta"`
	Data []struct {
		ID         string `json:"id"`
		Name       string `json:"name"`
		RemoteAddr string `json:"remote_addr"`
		CreatedAt  string `json:"created_at"`
	} `json:"data"`
}


func (c *DNSController) Index() {
	if c.GetString("token") == beego.AppConfig.String("DNSlogToke") {
		domain ,_ := c.GetInt("domainname")
		strdomain := strconv.Itoa(domain)
		if strdomain != "0" {
			c.Data["Domainname"] = strdomain
			// 解析返回请求
			var ReqJson Autogenerated
			errs := json.Unmarshal(GetCeyeData(strdomain), &ReqJson)
			if errs != nil {
				fmt.Println(errs)
			}
			c.Data["DomainInfo"] = ReqJson.Data
			c.Data["Token"] = c.GetString("token")
			c.TplName = "dnslog.html"
			return
		} else {
			// 这里是获取域名信息 输出一个随机的三级域名
			c.Data["Domainname"] = CreateCaptcha()
			c.Data["Token"] = c.GetString("token")
			c.TplName = "dnslog.html"
			return
		}
	} else {
		c.Ctx.Redirect(302, "/")
	}
}

// 刷新记录获取
func GetCeyeData(filter string) []byte {
	//http://api.ceye.io/v1/records\?token\=597a2b94b1816bf0638574399daa24d3\&type\=dns\&filter\=jljcxy
	CeyeToken := beego.AppConfig.String("CeyeToken")
	RequesrUrl := "http://api.ceye.io/v1/records?token="+CeyeToken+"&type=dns&filter="+filter
	resp, err := http.Get(RequesrUrl)
	if err != nil {
		fmt.Println("HTTP GET ",err)
	}
	defer resp.Body.Close()
	body, _ := ioutil.ReadAll(resp.Body)
	//fmt.Println(string(body))
	return body
}

// 生成六位随机数字
func CreateCaptcha() string {
	return fmt.Sprintf("%06v", rand.New(rand.NewSource(time.Now().UnixNano())).Int31n(1000000))
}
